version: "3.9"

services:

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ./config/.env
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - artblocks-stats-network

  collections-api:
    build:
      context: .
      dockerfile: docker/Dockerfile-api
    image: collections-api
    env_file:
      - ./config/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - artblocks-stats-network

networks:
  artblocks-stats-network: